name = "patel-flours"
main = "worker.ts"
compatibility_date = "2024-09-20"
compatibility_flags = ["nodejs_compat"]

# Environment variables (non-secret)
[vars]
ALLOWED_ORIGIN = "https://shop.gunjanpatel.info"

[[routes]]
pattern = "api.gunjanpatel.info"
zone_name= "gunjanpatel.info"
custom_domain = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "patel-flours"
database_id = "294c968e-9e5d-4cc0-b8ec-22ff087d1f04"
